[root@kunpeng1 opt]# k get deployments pas-d58f658e-4567-43c7-8ae5-d07ed253c060-sage-api-server -n prophet-resource-recommend -o yaml
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "11"
  creationTimestamp: 2020-02-17T08:30:56Z
  generation: 11
  labels:
    instanceId: "233"
  name: pas-d58f658e-4567-43c7-8ae5-d07ed253c060-sage-api-server
  namespace: prophet-resource-recommend
  resourceVersion: "180965820"
  selfLink: /apis/extensions/v1beta1/namespaces/prophet-resource-recommend/deployments/pas-d58f658e-4567-43c7-8ae5-d07ed253c060-sage-api-server
  uid: d182baca-515f-11ea-9b56-0894ef770d44
spec:
  replicas: 2
  selector:
    matchLabels:
      deploy: d58f658e-4567-43c7-8ae5-d07ed253c060
      prophet.4paradigm.com/pasDeployment: pas-d58f658e-4567-43c7-8ae5-d07ed253c060-sage-api-server
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        deploy: d58f658e-4567-43c7-8ae5-d07ed253c060
        instanceId: "233"
        prophet.4paradigm.com/pasDeployment: pas-d58f658e-4567-43c7-8ae5-d07ed253c060-sage-api-server
    spec:
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                - key: prophet.4paradigm.com/pasDeployment
                  operator: In
                  values:
                  - pas-d58f658e-4567-43c7-8ae5-d07ed253c060-sage-api-server
              topologyKey: kubernetes.io/hostname
            weight: 100
      automountServiceAccountToken: false
      containers:
      - env:
        - name: RANDOM_UUID
          value: random-e9964bdd
        - name: MY_POD_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.podIP
        - name: ACCESS_KEY
          value: 20095657-ebcf-47b0-a7df-ba9845eda841
        - name: NAME
          value: kfc-pt-yina
        - name: ENGINE_KEY
          value: kfc-pt-yina
        - name: INSTANCE_ID
          value: "233"
        - name: SC_KEY
          value: yumc-as
        - name: SC_VERSION
          value: 1.0.0
        - name: FLOW_ENGINE_URL
          value: http://automl-233:8080
        - name: TARGET_PORT
          value: "8080"
        - name: ENDPOINTS_ENV_ENABLED
          value: "false"
        - name: GO_MYSQL_PARAMS
          value: loc=Local&charset=utf8mb4&parseTime=True&time_zone=%27%2B08%3A00%27&maxAllowedPacket=0
        - name: HADOOP_ID
          value: primary
        - name: HADOOP_KEYTAB_BASE64
          value: BQIAAABCAAEAD0NOLllVTUNISU5BLkNPTQAQc3J2X2twX3JlY29tbWVuZAAAAAFcZlYOAQAXABApBjgLBXxpwWND7aR0Vycv
        - name: HADOOP_USER_NAME
          value: srv_kp_recommend
        - name: INJECTED_DB_HOST
          value: 172.25.203.254
        - name: INJECTED_DB_PASSWORD
          value: root
        - name: INJECTED_DB_PORT
          value: "3306"
        - name: INJECTED_DB_SALT
        - name: INJECTED_DB_USERNAME
          value: root
        - name: JDBC_MYSQL_PARAMS
          value: connectionCollation=utf8mb4_unicode_ci&useSSL=false&sessionVariables=time_zone%3d'%2B08%3A00'
        - name: PHT_NAMESPACE
          value: prophet
        - name: PHT_WORKSPACE_ID
          value: "15"
        - name: POD_META_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: POD_META_NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: PROPHET_LANG
          value: zh-CN
        - name: PROPHET_PAS_DEPLOYMENT_KEY
          value: sage-api-server
        - name: PROPHET_PAS_DEPLOYMENT_NAME
          value: pas-d58f658e-4567-43c7-8ae5-d07ed253c060-sage-api-server
        - name: PROPHET_PAS_ID
          value: d58f658e-4567-43c7-8ae5-d07ed253c060
        - name: TZ
          value: Asia/Shanghai
        image: 172.25.203.50:35000/env/release/kfc-preorder-tradeup/prophet/app/online-app-api-server.tar:pipe-404-commit-3b09b46a
        imagePullPolicy: Always
        lifecycle:
          preStop:
            exec:
              command:
              - /bin/bash
              - -c
              - sleep 20
        livenessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        name: kfc-pt-yina
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /actuator/health
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: "4"
            memory: 4096M
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /app/logs
          name: log-vol
        - mountPath: /app/conf/application.properties
          name: app-config-vol
          subPath: application.properties
        - mountPath: /app/conf/as_filebeat.yml
          name: filebeat-config-vol
          subPath: as_filebeat.yml
        - mountPath: /app/conf/log4j2.xml
          name: log-config-vol
          subPath: log4j2.xml
      dnsPolicy: ClusterFirstWithHostNet
      imagePullSecrets:
      - name: docker-secret
      nodeSelector:
        prophet.4paradigm.com/online: "true"
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: filebeat
            path: as_filebeat.yml
          name: online-app-api-server-233
        name: filebeat-config-vol
      - configMap:
          defaultMode: 420
          items:
          - key: log4j
            path: log4j2.xml
          name: online-app-api-server-233
        name: log-config-vol
      - configMap:
          defaultMode: 420
          items:
          - key: app-config
            path: application.properties
          name: online-app-api-server-233
        name: app-config-vol
      - emptyDir: {}
        name: log-vol
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: 2020-05-14T14:55:25Z
    lastUpdateTime: 2020-05-14T14:55:25Z
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  observedGeneration: 11
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2
