apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: jobflow-web
  namespace: ai-engineer
spec:
  replicas: 2
  # minReadySeconds: 30
  strategy:
    type: RollingUpdate
    rollingUpdate: 
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: jobflow-web
    spec:
      imagePullSecrets:
      - name: aie-registry-secret
      containers:
      - image: 172.25.203.50:35000/aie/kp-ai-jobflow-web:1.0-SNAPSHOT
        imagePullPolicy: Always
        name: jobflow-web
        env:
          - name: JOBFLOW_MYSQL_HOST
            value: jdbc:mysql://172.25.246.11:3306/kp_ai?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
        volumeMounts:
        - name : log
          mountPath: /data01/tmp
        ports:
        - containerPort: 8080
        resources:
          limits:
            cpu: "2"
            memory: 2Gi
      volumes:
        - name : log
          emptyDir: {}
---
kind: Service
apiVersion: v1
metadata:
  name: jobflow-web
  namespace: ai-engineer  
spec:
  type: NodePort
  selector:
    app: jobflow-web
  ports:
  - protocol: TCP
    port: 80 #ClusterIP:Port
    targetPort: 8080
    nodePort: 32279 #nodePort

